CREATE TABLE GITHUB_PROJECT (
  id        IDENTITY NOT NULL PRIMARY KEY,
  org_name  VARCHAR(50) NOT NULL,
  repo_name VARCHAR(50) NOT NULL UNIQUE,
);

CREATE INDEX idx_repo_name
  ON GITHUB_PROJECT (repo_name);
  
CREATE TABLE BOOK (
  id    IDENTITY NOT NULL PRIMARY KEY,
  title  VARCHAR(50) NOT NULL UNIQUE,
  author VARCHAR(50) NOT NULL,
);

CREATE INDEX idx_title
  ON BOOK (title);
  
CREATE TABLE EMPLOYEE (
  id    IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
);